version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: kitchen
    volumes:
      - /Users/gugadam/data/mongodb:/data/mongodb
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    networks:
      - web
    ports:
      - 27017:27017
    command: mongod

  mongo-express:
    image: mongo-express:latest
    container_name: "mongo-express"
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - web

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /Users/gugadam/data/redis:/data/redis
    ports:
    - 6379:6379
    command: redis-server

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181
    networks:
      - web

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONNECTIONS_FROM_HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_CREATE_TOPICS: "quickstart-events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9092:9092
      - 19092:19092
    networks:
      - web

networks:
  web:
    driver: bridge